apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selenium
  template:
    metadata:
      labels:
        app: selenium
    spec:
      containers:
        - name: selenium
          image: selenium-script:latest # This references the Docker image tag
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: selenium-configmap # Reference to the ConfigMap for non-sensitive data
            - secretRef:
                name: selenium-secrets # Reference to the Secret for sensitive data
---
# we can move this to a separate file later
apiVersion: v1
kind: ConfigMap
metadata:
  name: selenium-configmap
data:
  SMTP_SERVER: "smtp.gmail.com"
  SMTP_PORT: "587"
  FROM_EMAIL: "omnilabsdev@gmail.com"
  TO_EMAILS: "wwarkentin@fleetmetrica.com,btowne@fleetmetrica.com,chris@castlerooks.com"
---
# we can move this to a separate file later
apiVersion: v1
kind: Secret
metadata:
  name: selenium-secrets
type: Opaque
stringData:
  EMAIL: "chris@castlerooks.com"
  PASSWORD: "Ryan9753123!"
  OTP_SECRET: "Q3CJAMEBE5Q63QVHMI5G6E3EKL6G5L6A"
  FROM_EMAIL_PASSWORD: "syec peqx jwps kjmq"
